version: '3.7'

services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - backend-assignee
      - backend-asset
    expose:
      - ${REDIS_HOST}

volumes:
  redis-data:

networks:
  backend-assignee:
    external: true
    name: backend-assignee
    driver: bridge
  backend-asset:
    external: true
    name: backend-asset
    driver: bridge
