version: '3.7'

services:
  asset-ms:
    image: juliocardona/asset-ms
    container_name: asset-ms
    ports:
      - 8080:${ASSET_PORT}
    networks:
      - backend-asset
    restart: always
    environment:
      ASSET_MONGO_USERNAME: ${ASSET_MONGO_USERNAME}
      ASSET_MONGO_PASSWORD: ${ASSET_MONGO_PASSWORD}
      ASSET_MONGO_HOST: ${ASSET_MONGO_HOST}
      ASSET_MONGO_PORT: ${ASSET_MONGO_PORT}
      ASSIGNEE_HOST: ${ASSIGNEE_HOST}
      ASSIGNEE_PORT: ${ASSIGNEE_PORT}
      ASSET_MONGO_DB: ${ASSET_MONGO_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
  mongo-asset:
    container_name: mongo-asset
    image: mongo
    ## no se mapea los puertos ya que la bd unicamente sera accesible desde el ms
    volumes:
      - /mongo-data-asset-ms:/data/db
    networks:
      - backend-asset
    expose:
      - ${ASSET_MONGO_PORT}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ASSET_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ASSET_MONGO_INITDB_ROOT_PASSWORD}
networks:
  backend-asset:
    name: backend-asset
    driver: bridge