version: '3'

services:
  asset-ms:
    image: juliocardona/asset-ms
    container_name: asset-ms
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app/target
    networks:
      - backend-asset
  mongo-asset:
    container_name: mongo-asset
    image: mongo
    ## no se mapea los puertos ya que la bd unicamente sera accesible desde el ms
    volumes:
      - /mongo-data-asset-ms:/data/db
    networks:
      - backend-asset
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ASSET_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ASSET_MONGO_INITDB_ROOT_PASSWORD}
networks:
  backend-asset: